server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Send all requests to index.html (SPA routing)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: handle static files cache
    location ~* \.(?:manifest|appcache|html?|xml|json)$ {
        expires -1;
    }

    location ~* \.(?:css|js|gif|jpe?g|png|woff2?|svg|ttf|ico)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    error_page 404 /index.html;
}
